mc_platform_home:
    path:      /{page}
    defaults:  { _controller: MCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

mc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: MCPlatformBundle:Advert:view }
    requirements:
        id: \d+

mc_platform_add:
    path:      /add
    defaults:  { _controller: MCPlatformBundle:Advert:add }

mc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: MCPlatformBundle:Advert:edit }
    requirements:
        id: \d+

mc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: MCPlatformBundle:Advert:delete }
    requirements:
        id: \d+